class Questao():
    enunciado: str
    dica: str
    resposta_correta: str
    resposta_incorreta1: str
    resposta_incorreta2: str
    resposta_incorreta3: str
    resposta_incorreta4: str
    resposta_incorreta5: str
    # exercicio_id